-- Supplier groups + suppliers imported from document/mim data/Anis/smart_pur_suppliers_list.pdf
CREATE TABLE supplier_group (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code        VARCHAR(30)  NOT NULL UNIQUE,
    name        VARCHAR(160) NOT NULL,
    name_bn     VARCHAR(200),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

ALTER TABLE supplier ADD COLUMN group_id UUID REFERENCES supplier_group(id);
CREATE INDEX idx_supplier_group ON supplier(group_id);

INSERT INTO supplier_group (code, name) VALUES
    ('SG-01', 'Hardware Supplier'),
    ('SG-02', 'Sundry Creditors'),
    ('SG-03', 'OTHERS SUPPLIER'),
    ('SG-04', 'Ahmed Wood Crafts Ltd. (New)'),
    ('SG-05', 'Akij Particle Board Mills Ltd'),
    ('SG-06', 'Ambers Boards Mills Ltd.'),
    ('SG-07', 'Ashiq Plywood Ind.'),
    ('SG-08', 'Azad Ply Ltd.'),
    ('SG-09', 'Bengal Plywood Com. (2023)'),
    ('SG-10', 'City Plywood Ind.'),
    ('SG-11', 'Ahmed Wood Crafts Ltd. (Close)'),
    ('SG-12', 'Lira Doors Ltd. (2023)'),
    ('SG-13', 'M & B Plywood Ind.'),
    ('SG-14', 'M & B Plywood Ind (2024)'),
    ('SG-15', 'MRS Industries Ltd.'),
    ('SG-16', 'Maya Particle Mills (PVT) Ltd.'),
    ('SG-17', 'Meghna Pvc Sheet Com.'),
    ('SG-18', 'National Polymer Industries Ltd.'),
    ('SG-19', 'Oriantal ECo Woods Ltd.'),
    ('SG-20', 'Smart Eco Wood'),
    ('SG-21', 'STAR PARTICALE BOARD LID.'),
    ('SG-22', 'Star Pipe & Plastics Ltd. (PVC)'),
    ('SG-23', 'Super Board Ltd. BD.'),
    ('SG-24', 'Unique Wood Crafts & Plastic Ind.'),
    ('SG-25', 'Veneer Lab (Purchase)'),
    ('SG-26', 'Woodland Plywood Mills Ltd.');

INSERT INTO supplier (code, name, mobile, address, group_id) VALUES
    ('SUP-0001', 'A R Builders (HARDWAER)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0002', 'A R ENTERPRISE (HARDWARE)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0003', 'A&S Associate (Purchase)', NULL, 'Banani.', (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0004', 'A.E ENTERPRISE (HARDWARE)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0005', 'A.M Hardware (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0006', 'A.M.J ENTERPRISE (HARDWARE)', '01716-525321', 'KAWRAN BAZAR KABBAKASH MARKET', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0007', 'Abdullah Enterprise (Hardware)', '01672-399531', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0008', 'Abir Trading (Dulal Via) (Vages) (China P', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0009', 'ABS Associate (Trusty)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0010', 'Adhora Trading (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0011', 'Adhunik Hardware (hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0012', 'Advance Enterprise (Hardware)', '01918534855', 'K/B', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0013', 'Ahmed (Decor Board) New', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-04')),
    ('SUP-0014', 'Ahmed (HPL & Formica) New', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-04')),
    ('SUP-0015', 'Ahmed (PLY) New', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-04')),
    ('SUP-0016', 'Ahmed (PVC) New', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-04')),
    ('SUP-0017', 'Ahmed Edging (BOARD) New', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-04')),
    ('SUP-0018', 'Ahmed Edging (HARDWARE) New', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-04')),
    ('SUP-0019', 'Aidor Partical (Pur) Badda', '01774951518', NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0020', 'Akhie Hardware Store', '01727-440888', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0021', 'Akij Particle Board Mills Ltd', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-05')),
    ('SUP-0022', 'Akota Hardware (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0023', 'AL Amin Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0024', 'AL Arafah Hardware And Tools (Hardwa', '01705-167586', 'Kabbakash Super Market Kawran Bazar 0744-622505', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0025', 'Al Falah Hardware (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0026', 'Al Imdad Enterprise (Hardware)', '01726-266516', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0027', 'Al Insaf Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0028', 'Al Modina Hardware', '01818-314777', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0029', 'Al Monsur Enterprise (Hardware)', '01819-150741', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0030', 'Alauddin Metal Works (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0031', 'Albion Internationl (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0032', 'Ali Wire Nail (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0033', 'Alif Builders (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0034', 'Alif Hi-Tech Ind.Ltd', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0035', 'Allar Dan Traders', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0036', 'Amber Board Mills Ltd', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-06')),
    ('SUP-0037', 'Ambersha Lock House (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0038', 'Ami General Store', '01711-589913', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0039', 'Amin Builders (Hardware)', NULL, 'kawran bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0040', 'Anam Enterpris (Hardwaer)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0041', 'Anika Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0042', 'Archetive (Airolam)-Mohakhali', NULL, 'Mohakhali, Dhaka.', (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0043', 'ART LIFE INTERIOR & DESIGN (RAIN', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0044', 'Ashiq Plywood Industries Ltd.', '01812434771', 'Narayanganj', (SELECT id FROM supplier_group WHERE code = 'SG-07')),
    ('SUP-0045', 'ASIAN BUILDERS (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0046', 'AY ENTERPRISE (HARDWARE)', '01749-30023', NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0047', 'Ayesha Hardware (Hardware)', '01878-687311', NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0048', 'Azad Plywood Industries Ltd.', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-08')),
    ('SUP-0049', 'Aziz Lock House (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0050', 'Barek Hardware', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0051', 'Barishal Ent. (Jamal Bhai) Purchase', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0052', 'Bashundhara Hardwer (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0053', 'Beauty Plywood Industries Ltd.', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0054', 'Bengal Plywood (Extreme)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-09')),
    ('SUP-0055', 'Bengal Plywood (Joty & Eng. B.t)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-09')),
    ('SUP-0056', 'Bengal Plywood (N B.T)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-09')),
    ('SUP-0057', 'Bhai Bhai Enterprise (Khulna)', '01738104241', NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0058', 'Bhuiyan Enterprise (Hardware)', '01729-868502', 'kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0059', 'Billal Paint Suppliers (HARDWARE)', '01974-540581', 'kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0060', 'BIR GROUP HOLDINGS (HARDWARE', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0061', 'Bismillah Engineering Works (HARDWARE', '01967-923184', NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0062', 'Bismillah Enterprise (Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0063', 'Bismillah Stamp Bikoy Kendro (HARDWARE', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0064', 'Bistar Hardware (HARDWARE)', '01778-591009', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0065', 'Blue Print', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0066', 'Blulam (Purchase)', NULL, 'Banani, Dhaka.', (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0067', 'Century Hardware (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0068', 'City Plywood Ind.', '01300682912', '130, sainboard Bazar, , 682913', (SELECT id FROM supplier_group WHERE code = 'SG-10')),
    ('SUP-0069', 'Close Ahmed (Edging)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-11')),
    ('SUP-0070', 'Close Ahmed (MLB)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-11')),
    ('SUP-0071', 'Close Ahmed (PLY) Close', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-11')),
    ('SUP-0072', 'Close Ahmed (PVC)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-11')),
    ('SUP-0073', 'Close Ahmed (Veneer) Close', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-11')),
    ('SUP-0074', 'Cosmic Decore (Luxury)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0075', 'Crystal Plus (Hardware Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0076', 'Crystal Plus (Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0077', 'D S Hardware (HARDWARE)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0078', 'Decor Interior (Mohakhali)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0079', 'Decorama Intorior (Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0080', 'Decorative Sheet', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0081', 'Desh Bangla Metal & Hardware', '01961-033431', NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0082', 'Design Studio (Mohakhali)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0083', 'Dhaka Ply/World Trade Com (Malak Va', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0084', 'Dhoher Traders Babul Vai (Purshes)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0085', 'Dhusor Swapno (Live Space) ( Purchas', NULL, 'Sylet Merin Academy', (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0086', 'Dong Fang Industrial Dev. Co. Ltd.', '01301793818', 'Natore Tower, Plot#32-D/E, Floor#6, Road#2, Sector #3, Uttara, Dhaka-1230', (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0087', 'Dream Builders (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0088', 'Drem Builders (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0089', 'Eastern Corporation (Hardware)', '01845-533333', 'Kazi Nazrul Islam Avenue. dhaka-1215 . 01918-946893', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0090', 'Eco Trade BD.', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0091', 'EHBL Hardware Karwanbazar (Hardwa', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0092', 'ELEGANCE SPACE (PURCHASE)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0093', 'ELEVATE INTERNATIONAL(HARDWAR', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0094', 'Ema Trade International (Hardware)', '01822-870376', 'shop-109, Kabbacosh super market 1st floor Kawran Bazar 01929-716263', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0095', 'Emarat Builders (hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0096', 'Emon Brothers (Younus Ali, Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0097', 'Euro Hardware Center (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0098', 'Fahim Timber & Sawmill', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0099', 'Faisal Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0100', 'Famous Hardware Store (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0101', 'Fast Corporation PVT. LTD-purchase (', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0102', 'Fatema Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0103', 'Fatema Hasan Traders (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0104', 'Fatema Trading Corporation (Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0105', 'Fency Hardware (Hardware)', NULL, 'kawranbazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0106', 'Fervent Multiboard Ind. Ltd.', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0107', 'Fevicol (J. R Traders)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0108', 'Fixway (Hardware)', '01312-858123', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0109', 'Forazi Hardware Purchase A/P(Hardwar', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0110', 'Freedom Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0111', 'Freedom Trade Link (Pur)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0112', 'Godhuli Hardware (Hardware)', NULL, 'Kawranbazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0113', 'Golden Hardware (Hardware)', NULL, 'Kawranbazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0114', 'Golden Trade Internatoional', NULL, 'Midfort Imamgonj', (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0115', 'Green Board Mills Ltd.', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0116', 'Green Touch F.I International', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0117', 'Grind Tech Ltd (Hardware)', '01708-121222', NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0118', 'Gulshan Vitex HPL (Samrat)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0119', 'H F Hardware (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0120', 'Habib Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0121', 'HAFELE (HARDWARE)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0122', 'Hamid Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0123', 'Hanif Traders (Hardware Purchase)', NULL, 'kawranbazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0124', 'Hanufa (Kawran Bazar) (Pur)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0125', 'Hardware plus (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0126', 'HARDWARE PURCHASE ACCOUNT', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0127', 'Hasan Builders (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0128', 'Hassan Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0129', 'Havel Hardware (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0130', 'Heaven Homes Materials (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0131', 'Hi Care (Hardware)', '01877-040404', NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0132', 'HI-CLASS LUXURY HARDWARE GOOD', '01711-335704', '248/3 TEJGAON IND.AREA 01674-609813', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0133', 'HUMAYAN CAR CAINT (HARDWARE)', '01914-128339', 'KABOCOS SUPER MARKET. KARWAN BAZAR DHAKA . -01751-760474', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0134', 'IMTEAZ AND BROTHERS (Hardware)', '01742922383', 'kabbakas super market karwan bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0135', 'Interior Designer (Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0136', 'ISLAM ENTERPRISE (HARDWARE)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0137', 'Ittadi Hardware (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0138', 'J H ENTERPRISE (HARDWARE)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0139', 'J M TRADE INTERNATIONAL (Hardwa', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0140', 'J.B.L Enterprise (Hardware)', NULL, 'Kawranbazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0141', 'J.M Traders (HArdware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0142', 'JAKIA BUILDERS HARDWARE AND P', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0143', 'Jamuna Hardware Store (Hardware)', '01611-522674', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0144', 'Janata Hardware (Hardware)', '01732-398679', 'Kabbokas kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0145', 'Jara Enterprise (Hardware)', '01732-398679', 'Kawra Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0146', 'Jarz Enterprise', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0147', 'Jehad Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0148', 'Jia Vai (New) (Impoter Karosin Kat)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0149', 'Jia Vai Impoter (Karosin Kat-2020)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0150', 'JK International (Hardware)', NULL, 'kawranbazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0151', 'Johir Vai (Rayer Bazar) Chaina Board', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0152', 'JUBAYED ENTERPRISE (HARDWARE', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0153', 'Jui Hardware Purchase (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0154', 'Junayad Hardware & Suppliers (Hardwa', '01743-830232', 'kawranbazza', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0155', 'Junayed Enterprise (Purchase)', NULL, 'Basabo, Dhaka.', (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0156', 'K R Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0157', 'Kabir Builders (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0158', 'Kakon Particle Board Agency', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0159', 'Karim Enterprise (Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0160', 'Khaja Enterprise (China)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0161', 'Khondoker Hardware (Hardware)', '01952-888441', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0162', 'Korim Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0163', 'Kouser Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0164', 'KS INTERNATIONAL (Plywood Center)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0165', 'Latest Interior (Fortun)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0166', 'Laxmipur Tools & Machinaries (Hardwar', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0167', 'LEVEL 5 CORPORATION (PURCHASE', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0168', 'Lira Doors Ltd. 2023', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-12')),
    ('SUP-0169', 'LockTech Hardware Trading (Hardware)', '01645-427007', 'Shop No 99,1st Floor Kabbokas market Kawran Bazar 01946-804434', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0170', 'Luxury Hardware (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0171', 'M & B Plywood Ind. (Closed/23)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-13')),
    ('SUP-0172', 'M & B Plywood Industries Ltd.', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-14')),
    ('SUP-0173', 'M K Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0174', 'M P L Tech (Baridhara)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0175', 'M R C LIMITED (Pur.)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0176', 'M R S Industrise Ltd.', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-15')),
    ('SUP-0177', 'M R Traders (Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0178', 'M S Hardware Store (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0179', 'M/S. K.S. Corporation (China)', '01711149091', 'senpara, parbata, mirpur', (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0180', 'Ma Babar Duya Hardware Stor (Hardwa', '01716-091967', 'kabbakas super market kawran bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0181', 'Ma Enterprise (Hardware)', '01714-617424', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0182', 'MAA Paint', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0183', 'Mahmuda Enterprise (Hadware)', '01827-304940', 'Kawrnbazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0184', 'Mamun Builders (Nababpur)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0185', 'Mannan Traders (Purshes) (K.N.A)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0186', 'Master Point (Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0187', 'Maxmart C.N.C & Pesting (Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0188', 'Maya Partical Ltd. (2024)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-16')),
    ('SUP-0189', 'Mayer Dowa Hardware & Paints (Hardw', '01827-772147', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0190', 'Meem Enterprise (Hardware)', '01819-167151', 'Kabbbakas super market kawran bazar .Dhaka. . 01841-450042', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0191', 'Meghna Pvc Sheet Com.', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-17')),
    ('SUP-0192', 'Mim Enterprise-2 Dhar Khat', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0193', 'MIR Brothers (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0194', 'Mithin Traders (Loose Venear)', '01712-514520', '01850475433', (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0195', 'MIzan (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0196', 'Mobarak Hossen & Brothers (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0197', 'Modina Ent. (Nayabazar)', '01819-292896', '01979-292896, 01911-797989', (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0198', 'Mohammad Trading (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0199', 'Monir Hardware & Electric (Hardware)', '01712-291850', NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0200', 'MOON INTERNATIONAL (HARDWARE', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0201', 'Moriom Particle Board', '01711812992', '1st November 2022 To 31 Oct/23', (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0202', 'Mothbariya Boylar (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0203', 'Mozaffor Vai (M.H Trade) (Purses)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0204', 'Murad Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0205', 'N N Builders (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0206', 'Nagar Builders (Hardware)', '01730-191103', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0207', 'Nahid Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0208', 'Naim Enterprise (Marinolam)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0209', 'Nasir Bhai (Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0210', 'National Hardware (HARDWARE)', '01850-383027', 'Kabbakas super market kawran bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0211', 'National Polymer Industies Ltd.', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-18')),
    ('SUP-0212', 'Nazim Hardware Store (Puechase) (Har', '01775-553761', NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0213', 'New Dalia Hardware Store (Hardware)', '01711-288541', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0214', 'New Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0215', 'New Janata Hardware Store (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0216', 'NEW MAKKA METAL (HARDWARE)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0217', 'New Rahman Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0218', 'NEW SR ENTERPRISE (SRM)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0219', 'NUHA TRADING (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0220', 'Nur Modina Builders (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0221', 'OASIS (VIRA)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0222', 'Odud Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0223', 'OLympia Paint & Hardware (Haedware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0224', 'Omi Enterprise (Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0225', 'One Hardware (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0226', 'Open Source-Purchase (Mohammadpur', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0227', 'Oriental Eco Woods Ltd. (PVC)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-19')),
    ('SUP-0228', 'Oriental Eco Woods Ltd. (WPC)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-19')),
    ('SUP-0229', 'Pabna Traders (Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0230', 'Parents Hardware (Hardware)', '01829-020403', 'Kabbokas Super Market Shop no-37 Kawran Bazar dhak', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0231', 'Patoary Badda (Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0232', 'PATWARY HARDWARE (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0233', 'Plywood Center (Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0234', 'Poly HPL Plywood Ltd.', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0235', 'Poran Hardware (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0236', 'Prime Builders (Puechase) (Hardware)', '01911-631443', 'Kabbkas Kawrnbazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0237', 'Prime Corporation Bd', '01911-317494', 'kabbakas market', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0238', 'Prime Hardware (Hardware)', '01754-945818', NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0239', 'PRIME SOLUTION (BELADOR)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0240', 'Probasi Hardware (Hardware)', '01972-099523', 'Karwar Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0241', 'Progoti Ent. (Pursh)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0242', 'R R Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0243', 'R.H .M INT. (HARDWARE)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0244', 'R.S Enterprise (Hardware)', '01839-961145', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0245', 'Rafi Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0246', 'Rafia Car Paint (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0247', 'Rahman & Sons (KNA) (Purshes)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0248', 'Rahman Trading Corproration (Purshes)', '01711907871', 'Boshundhara, Asuliya, Tongi , 01727342215', (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0249', 'Rajdhani Enterprise', '01822-988633', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0250', 'Rajdhani Hardware (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0251', 'Ramgonj Hardware & Machinarig (Har', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0252', 'Rangdhanu Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0253', 'RFL Industries Limited', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0254', 'Rifat Vai (losse Venear)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0255', 'Riyadh Enterprise (Hardware)', NULL, 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0256', 'RM International (Hardware)', '01854-888457', 'kabbokash super market kawran bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0257', 'Rony Enterprise (Bengal Pvc)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0258', 'Rony Plywood Industries (Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0259', 'S K Rahman Timber & Pasting (Purcha', NULL, 'Kawran Bazar, Dhaka.', (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0260', 'S R Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0261', 'S.M Enterprise (Abul Vai)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0262', 'S.N International (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0263', 'S.S Hardware Store (Hardware)', '01974-339933', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0264', 'Saat Trading', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0265', 'Sadek Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0266', 'Saif Hardware & Tools (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0267', 'SAIFUL ENTERPRISE (HARDWARE)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0268', 'Salman Enterprise (Hardware)', NULL, 'kawranbazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0269', 'San Trading (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0270', 'SELIM HARDWARE (HARDWARE)', '01916-665533', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0271', 'Shabab Trade International (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0272', 'Shahin Builders (Hardware)', '01629-105420', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0273', 'Shahjahan Traders (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0274', 'Shakhayat Timber (Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0275', 'Shakil Enterprise (Purchase)', NULL, 'Shahjadpur, Badda, Dhaka.', (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0276', 'Shati Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0277', 'Shohag Hardware Store', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0278', 'Shohid Ent. (KB) (Pur)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0279', 'SHOWROV HARDWARE (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0280', 'Shuvo Hardware & Interior (Hardware)', NULL, 'Kawranbazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0281', 'Sign Packeging Store Purchase', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0282', 'Sis International (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0283', 'SKF Builders (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0284', 'SKF Hardware (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0285', 'SKY BUSINESS CENTER (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0286', 'Sky Decor (Mohakhali)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0287', 'Smart Eco Wood', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-20')),
    ('SUP-0288', 'SMS Corporation (Yellow)(Hardware)', '01711-027219', 'House-569, Ahmed Alli Sarkar Bari Rall Gate Azampur Uttara', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0289', 'Soharob Enterprise (Hardware)', NULL, 'kawranbazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0290', 'SOHEL & BROTHERS (HARDWARE)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0291', 'Sohrab Enterprise (HARDWARE)', '01712-171335', 'Kabbakas super market karwan bazar . 01837-356207', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0292', 'SOMRAT HARDWARE (HARDWARE)', '01715-752174', 'Kabbkos super market kawran bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0293', 'SP CORPORATION (REBECCA)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0294', 'SRS ENTERPRISE (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0295', 'Star Door', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-21')),
    ('SUP-0296', 'Star Hardware (Hardware)', '01973-946457', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0297', 'Star Losse Venear', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-21')),
    ('SUP-0298', 'Star Partical Board Mills Ltd. (MDF)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-21')),
    ('SUP-0299', 'Star Particle Board Mills Ltd (MLB)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-21')),
    ('SUP-0300', 'Star Particle Board Mills Ltd (PB)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-21')),
    ('SUP-0301', 'Star Particle Board Mills Ltd (Ply)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-21')),
    ('SUP-0302', 'Star Particle Board Mills Ltd (VB)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-21')),
    ('SUP-0303', 'Star Particle Board Mills Ltd. (PVC)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-21')),
    ('SUP-0304', 'Star Pipes & Plastics Ltd. (PVC)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-22')),
    ('SUP-0305', 'Star Zipsam (Star)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-21')),
    ('SUP-0306', 'SUJON METAL WORKS(HARDWARE)', '01912-352899', 'CHA-97/1, PROGATI SHORNI UTTOR BADDA , 01942-240627', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0307', 'Sumon Enterprise (39/kha, Sanpara)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0308', 'Sun Corporation (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0309', 'Sundarbon Plywood Industries', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0310', 'Super Board Mills Ltd.', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-23')),
    ('SUP-0311', 'Super- Harun & Sons', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-23')),
    ('SUP-0312', 'Suzon International/ Era Trade Internat', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0313', 'T A Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0314', 'T M A Enterprise (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0315', 'Tahmid Enterprise (Hardware)', '01743-565584', 'kabbakos super market kawran bazer dhaka-1215 . 01877-145082', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0316', 'Taj Hardware', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0317', 'Tarek Hardware', '01837-392515', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0318', 'Tezart Hardware & Nut Bolt', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0319', 'The Asian Tools & Machinaries', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0320', 'Tri T International', '01711-463360', 'B C C Road', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0321', 'Unique Hardware', NULL, 'kawranbazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0322', 'Unique Wood Crafts & Plastic Ind.', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-24')),
    ('SUP-0323', 'UP Enterprise CNC & Pasting (Purchas', NULL, 'Kawranbazar, Dhaka.', (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0324', 'Uzala Paint & Electric', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0325', 'Veneer House (Bonani) -Purchase', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0326', 'Veneer Lab (Loose Veneer)', '01712847898', 'Kushtia', (SELECT id FROM supplier_group WHERE code = 'SG-25')),
    ('SUP-0327', 'Veneer Lab (PVC)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-25')),
    ('SUP-0328', 'Vira Eshop (HPL)', '01710-735425', 'HOUSE-65, AIRPORT ROAD, AMTOLI MOHAKHALI , 01324-430921', (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0329', 'Wood World Plywood Industry', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0330', 'Woodland Plywood Mills Ltd.', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-26')),
    ('SUP-0331', 'Woodtech Plywood (Pvt) Ltd', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03')),
    ('SUP-0332', 'Yasin Printers (Hardware)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0333', 'YEASIN BUILDERS', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0334', 'Yousuf Enterprise', '01977-222126', 'Kawran Bazar', (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0335', 'Zakir Bhai (RFL Officer)-Purchase', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0336', 'Zam Zam Interior (Hardware Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-01')),
    ('SUP-0337', 'Zia Sir Amber (Purchase)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-02')),
    ('SUP-0338', 'Zinnat Enterprise (China)', NULL, NULL, (SELECT id FROM supplier_group WHERE code = 'SG-03'));
