-- Best-effort automated Bangla transliteration of supplier names (dictionary + phonetic fallback)
UPDATE supplier SET name_bn = 'এ আর বিল্ডার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0001';
UPDATE supplier SET name_bn = 'এ আর এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0002';
UPDATE supplier SET name_bn = 'এ অ্যান্ড এস অ্যাসোসিয়েট (ক্রয়)' WHERE code = 'SUP-0003';
UPDATE supplier SET name_bn = 'এ.ই এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0004';
UPDATE supplier SET name_bn = 'এ.এম হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0005';
UPDATE supplier SET name_bn = 'এ.এম.জে এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0006';
UPDATE supplier SET name_bn = 'আব্দুল্লাহ এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0007';
UPDATE supplier SET name_bn = 'আবির ট্রেডিং (দুলাল ভায়া) (ভেজেস) (চায়না পি' WHERE code = 'SUP-0008';
UPDATE supplier SET name_bn = 'এবিএস অ্যাসোসিয়েট (ট্রাস্টি)' WHERE code = 'SUP-0009';
UPDATE supplier SET name_bn = 'আধরা ট্রেডিং (হার্ডওয়্যার)' WHERE code = 'SUP-0010';
UPDATE supplier SET name_bn = 'আধুনিক হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0011';
UPDATE supplier SET name_bn = 'অ্যাডভান্স এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0012';
UPDATE supplier SET name_bn = 'আহমেদ (ডেকর বোর্ড) নতুন' WHERE code = 'SUP-0013';
UPDATE supplier SET name_bn = 'আহমেদ (এইচপিএল অ্যান্ড ফরমাইকা) নতুন' WHERE code = 'SUP-0014';
UPDATE supplier SET name_bn = 'আহমেদ (প্লাই) নতুন' WHERE code = 'SUP-0015';
UPDATE supplier SET name_bn = 'আহমেদ (পিভিসি) নতুন' WHERE code = 'SUP-0016';
UPDATE supplier SET name_bn = 'আহমেদ এজিং (বোর্ড) নতুন' WHERE code = 'SUP-0017';
UPDATE supplier SET name_bn = 'আহমেদ এজিং (হার্ডওয়্যার) নতুন' WHERE code = 'SUP-0018';
UPDATE supplier SET name_bn = 'আইডর পার্টিকেল (ক্রয়) বাড্ডা' WHERE code = 'SUP-0019';
UPDATE supplier SET name_bn = 'আখি হার্ডওয়্যার স্টোর' WHERE code = 'SUP-0020';
UPDATE supplier SET name_bn = 'আকিজ পার্টিকেল বোর্ড মিলস লিঃ' WHERE code = 'SUP-0021';
UPDATE supplier SET name_bn = 'অকোটা হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0022';
UPDATE supplier SET name_bn = 'আল আমিন এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0023';
UPDATE supplier SET name_bn = 'আল আরাফাহ হার্ডওয়্যার অ্যান্ড টুলস (হার্ডওয়্যার' WHERE code = 'SUP-0024';
UPDATE supplier SET name_bn = 'আল ফালাহ হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0025';
UPDATE supplier SET name_bn = 'আল ইমদাদ এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0026';
UPDATE supplier SET name_bn = 'আল ইনসাফ এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0027';
UPDATE supplier SET name_bn = 'আল মদিনা হার্ডওয়্যার' WHERE code = 'SUP-0028';
UPDATE supplier SET name_bn = 'আল মনসুর এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0029';
UPDATE supplier SET name_bn = 'আলাউদ্দিন মেটাল ওয়ার্কস (হার্ডওয়্যার)' WHERE code = 'SUP-0030';
UPDATE supplier SET name_bn = 'অ্যালবিওন ইন্টারন্যাশনাল (হার্ডওয়্যার)' WHERE code = 'SUP-0031';
UPDATE supplier SET name_bn = 'আলী ওয়্যার নেইল (হার্ডওয়্যার)' WHERE code = 'SUP-0032';
UPDATE supplier SET name_bn = 'আলিফ বিল্ডার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0033';
UPDATE supplier SET name_bn = 'আলিফ হাই-টেক ইন্ডাস্ট্রিজ.লিঃ' WHERE code = 'SUP-0034';
UPDATE supplier SET name_bn = 'আল্লার দান ট্রেডার্স' WHERE code = 'SUP-0035';
UPDATE supplier SET name_bn = 'অ্যাম্বার বোর্ড মিলস লিঃ' WHERE code = 'SUP-0036';
UPDATE supplier SET name_bn = 'আম্বরশা লক হাউস (হার্ডওয়্যার)' WHERE code = 'SUP-0037';
UPDATE supplier SET name_bn = 'আমি জেনারেল স্টোর' WHERE code = 'SUP-0038';
UPDATE supplier SET name_bn = 'আমিন বিল্ডার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0039';
UPDATE supplier SET name_bn = 'আনাম এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0040';
UPDATE supplier SET name_bn = 'অনিকা এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0041';
UPDATE supplier SET name_bn = 'আর্কাটিভ (এয়ারোলাম)-মহাখালী' WHERE code = 'SUP-0042';
UPDATE supplier SET name_bn = 'আর্ট লাইফ ইন্টেরিয়র অ্যান্ড ডিজাইন (রেইন' WHERE code = 'SUP-0043';
UPDATE supplier SET name_bn = 'আশিক প্লাইউড ইন্ডাস্ট্রিজ লিঃ.' WHERE code = 'SUP-0044';
UPDATE supplier SET name_bn = 'এশিয়ান বিল্ডার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0045';
UPDATE supplier SET name_bn = 'এওয়াই এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0046';
UPDATE supplier SET name_bn = 'আয়েশা হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0047';
UPDATE supplier SET name_bn = 'আজাদ প্লাইউড ইন্ডাস্ট্রিজ লিঃ.' WHERE code = 'SUP-0048';
UPDATE supplier SET name_bn = 'আজিজ লক হাউস (হার্ডওয়্যার)' WHERE code = 'SUP-0049';
UPDATE supplier SET name_bn = 'বারেক হার্ডওয়্যার' WHERE code = 'SUP-0050';
UPDATE supplier SET name_bn = 'বরিশাল এন্টারপ্রাইজ. (জামাল ভাই) ক্রয়' WHERE code = 'SUP-0051';
UPDATE supplier SET name_bn = 'বসুন্ধরা হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0052';
UPDATE supplier SET name_bn = 'বিউটি প্লাইউড ইন্ডাস্ট্রিজ লিঃ.' WHERE code = 'SUP-0053';
UPDATE supplier SET name_bn = 'বেঙ্গল প্লাইউড (এক্সট্রিম)' WHERE code = 'SUP-0054';
UPDATE supplier SET name_bn = 'বেঙ্গল প্লাইউড (জ্যোতি অ্যান্ড ইঞ্জি. বি.টি)' WHERE code = 'SUP-0055';
UPDATE supplier SET name_bn = 'বেঙ্গল প্লাইউড (এন বি.টি)' WHERE code = 'SUP-0056';
UPDATE supplier SET name_bn = 'ভাই ভাই এন্টারপ্রাইজ (খুলনা)' WHERE code = 'SUP-0057';
UPDATE supplier SET name_bn = 'ভূঁইয়া এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0058';
UPDATE supplier SET name_bn = 'বিলাল পেইন্ট সাপ্লায়ার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0059';
UPDATE supplier SET name_bn = 'বীর গ্রুপ হোল্ডিংস (হার্ডওয়্যার' WHERE code = 'SUP-0060';
UPDATE supplier SET name_bn = 'বিসমিল্লাহ ইঞ্জিনিয়ারিং ওয়ার্কস (হার্ডওয়্যার' WHERE code = 'SUP-0061';
UPDATE supplier SET name_bn = 'বিসমিল্লাহ এন্টারপ্রাইজ (ক্রয়)' WHERE code = 'SUP-0062';
UPDATE supplier SET name_bn = 'বিসমিল্লাহ স্ট্যাম্প বিক্রয় কেন্দ্র (হার্ডওয়্যার' WHERE code = 'SUP-0063';
UPDATE supplier SET name_bn = 'বিস্তার হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0064';
UPDATE supplier SET name_bn = 'ব্লু প্রিন্ট' WHERE code = 'SUP-0065';
UPDATE supplier SET name_bn = 'ব্লুলাম (ক্রয়)' WHERE code = 'SUP-0066';
UPDATE supplier SET name_bn = 'সেঞ্চুরি হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0067';
UPDATE supplier SET name_bn = 'সিটি প্লাইউড ইন্ডাস্ট্রিজ.' WHERE code = 'SUP-0068';
UPDATE supplier SET name_bn = 'বন্ধ আহমেদ (এজিং)' WHERE code = 'SUP-0069';
UPDATE supplier SET name_bn = 'বন্ধ আহমেদ (এমএলবি)' WHERE code = 'SUP-0070';
UPDATE supplier SET name_bn = 'বন্ধ আহমেদ (প্লাই) বন্ধ' WHERE code = 'SUP-0071';
UPDATE supplier SET name_bn = 'বন্ধ আহমেদ (পিভিসি)' WHERE code = 'SUP-0072';
UPDATE supplier SET name_bn = 'বন্ধ আহমেদ (ভিনিয়ার) বন্ধ' WHERE code = 'SUP-0073';
UPDATE supplier SET name_bn = 'কসমিক ডেকর (লাক্সারি)' WHERE code = 'SUP-0074';
UPDATE supplier SET name_bn = 'ক্রিস্টাল প্লাস (হার্ডওয়্যার ক্রয়)' WHERE code = 'SUP-0075';
UPDATE supplier SET name_bn = 'ক্রিস্টাল প্লাস (ক্রয়)' WHERE code = 'SUP-0076';
UPDATE supplier SET name_bn = 'ডি এস হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0077';
UPDATE supplier SET name_bn = 'ডেকর ইন্টেরিয়র (মহাখালী)' WHERE code = 'SUP-0078';
UPDATE supplier SET name_bn = 'ডেকোরামা ইন্টেরিয়র (ক্রয়)' WHERE code = 'SUP-0079';
UPDATE supplier SET name_bn = 'ডেকোরেটিভ শিট' WHERE code = 'SUP-0080';
UPDATE supplier SET name_bn = 'দেশ বাংলা মেটাল অ্যান্ড হার্ডওয়্যার' WHERE code = 'SUP-0081';
UPDATE supplier SET name_bn = 'ডিজাইন স্টুডিও (মহাখালী)' WHERE code = 'SUP-0082';
UPDATE supplier SET name_bn = 'ঢাকা প্লাই/ওয়ার্ল্ড ট্রেড কোম্পানি (মালিক ভা' WHERE code = 'SUP-0083';
UPDATE supplier SET name_bn = 'ধোহের ট্রেডার্স বাবুল ভাই (ক্রয়)' WHERE code = 'SUP-0084';
UPDATE supplier SET name_bn = 'ধূসর স্বপ্ন (লাইভ স্পেস) ( ক্রয়' WHERE code = 'SUP-0085';
UPDATE supplier SET name_bn = 'ডং ফাং ইন্ডাস্ট্রিয়াল ডেভ. কোং. লিঃ.' WHERE code = 'SUP-0086';
UPDATE supplier SET name_bn = 'ড্রিম বিল্ডার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0087';
UPDATE supplier SET name_bn = 'ড্রিম বিল্ডার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0088';
UPDATE supplier SET name_bn = 'ইস্টার্ন কর্পোরেশন (হার্ডওয়্যার)' WHERE code = 'SUP-0089';
UPDATE supplier SET name_bn = 'ইকো ট্রেড বিডি.' WHERE code = 'SUP-0090';
UPDATE supplier SET name_bn = 'ইএইচবিএল হার্ডওয়্যার কারওয়ান বাজার (হার্ডওয়্যার' WHERE code = 'SUP-0091';
UPDATE supplier SET name_bn = 'এলিগ্যান্স স্পেস (ক্রয়)' WHERE code = 'SUP-0092';
UPDATE supplier SET name_bn = 'এলিভেট ইন্টারন্যাশনাল(হার্ডওয়্যার' WHERE code = 'SUP-0093';
UPDATE supplier SET name_bn = 'এমা ট্রেড ইন্টারন্যাশনাল (হার্ডওয়্যার)' WHERE code = 'SUP-0094';
UPDATE supplier SET name_bn = 'এমারত বিল্ডার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0095';
UPDATE supplier SET name_bn = 'এমন ব্রাদার্স (ইউনুস আলী, ক্রয়)' WHERE code = 'SUP-0096';
UPDATE supplier SET name_bn = 'ইউরো হার্ডওয়্যার সেন্টার (হার্ডওয়্যার)' WHERE code = 'SUP-0097';
UPDATE supplier SET name_bn = 'ফাহিম টিম্বার অ্যান্ড স-মিল' WHERE code = 'SUP-0098';
UPDATE supplier SET name_bn = 'ফয়সাল এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0099';
UPDATE supplier SET name_bn = 'ফেমাস হার্ডওয়্যার স্টোর (হার্ডওয়্যার)' WHERE code = 'SUP-0100';
UPDATE supplier SET name_bn = 'ফাস্ট কর্পোরেশন প্রাঃ. লিঃ-ক্রয় (' WHERE code = 'SUP-0101';
UPDATE supplier SET name_bn = 'ফাতেমা এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0102';
UPDATE supplier SET name_bn = 'ফাতেমা হাসান ট্রেডার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0103';
UPDATE supplier SET name_bn = 'ফাতেমা ট্রেডিং কর্পোরেশন (ক্রয়)' WHERE code = 'SUP-0104';
UPDATE supplier SET name_bn = 'ফ্যান্সি হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0105';
UPDATE supplier SET name_bn = 'ফারভেন্ট মাল্টিবোর্ড ইন্ডাস্ট্রিজ. লিঃ.' WHERE code = 'SUP-0106';
UPDATE supplier SET name_bn = 'ফেভিকল (জে. আর ট্রেডার্স)' WHERE code = 'SUP-0107';
UPDATE supplier SET name_bn = 'ফিক্সওয়ে (হার্ডওয়্যার)' WHERE code = 'SUP-0108';
UPDATE supplier SET name_bn = 'ফরাজী হার্ডওয়্যার ক্রয় এ/পি(হার্ডওয়্যার' WHERE code = 'SUP-0109';
UPDATE supplier SET name_bn = 'ফ্রিডম এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0110';
UPDATE supplier SET name_bn = 'ফ্রিডম ট্রেড লিংক (ক্রয়)' WHERE code = 'SUP-0111';
UPDATE supplier SET name_bn = 'গোধূলি হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0112';
UPDATE supplier SET name_bn = 'গোল্ডেন হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0113';
UPDATE supplier SET name_bn = 'গোল্ডেন ট্রেড ইন্টারন্যাশনাল' WHERE code = 'SUP-0114';
UPDATE supplier SET name_bn = 'গ্রিন বোর্ড মিলস লিঃ.' WHERE code = 'SUP-0115';
UPDATE supplier SET name_bn = 'গ্রিন টাচ এফ.আই ইন্টারন্যাশনাল' WHERE code = 'SUP-0116';
UPDATE supplier SET name_bn = 'গ্রাইন্ড টেক লিঃ (হার্ডওয়্যার)' WHERE code = 'SUP-0117';
UPDATE supplier SET name_bn = 'গুলশান ভিটেক্স এইচপিএল (সম্রাট)' WHERE code = 'SUP-0118';
UPDATE supplier SET name_bn = 'এইচ এফ হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0119';
UPDATE supplier SET name_bn = 'হাবিব এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0120';
UPDATE supplier SET name_bn = 'হাফেলে (হার্ডওয়্যার)' WHERE code = 'SUP-0121';
UPDATE supplier SET name_bn = 'হামিদ এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0122';
UPDATE supplier SET name_bn = 'হানিফ ট্রেডার্স (হার্ডওয়্যার ক্রয়)' WHERE code = 'SUP-0123';
UPDATE supplier SET name_bn = 'হানুফা (কাওরান বাজার) (ক্রয়)' WHERE code = 'SUP-0124';
UPDATE supplier SET name_bn = 'হার্ডওয়্যার প্লাস (হার্ডওয়্যার)' WHERE code = 'SUP-0125';
UPDATE supplier SET name_bn = 'হার্ডওয়্যার ক্রয় অ্যাকাউন্ট' WHERE code = 'SUP-0126';
UPDATE supplier SET name_bn = 'হাসান বিল্ডার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0127';
UPDATE supplier SET name_bn = 'হাসান এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0128';
UPDATE supplier SET name_bn = 'হ্যাভেল হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0129';
UPDATE supplier SET name_bn = 'হেভেন হোমস ম্যাটেরিয়ালস (হার্ডওয়্যার)' WHERE code = 'SUP-0130';
UPDATE supplier SET name_bn = 'হাই কেয়ার (হার্ডওয়্যার)' WHERE code = 'SUP-0131';
UPDATE supplier SET name_bn = 'হাই-ক্লাস লাক্সারি হার্ডওয়্যার গুড' WHERE code = 'SUP-0132';
UPDATE supplier SET name_bn = 'হুমায়ূন কার পেইন্ট (হার্ডওয়্যার)' WHERE code = 'SUP-0133';
UPDATE supplier SET name_bn = 'ইমতিয়াজ অ্যান্ড ব্রাদার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0134';
UPDATE supplier SET name_bn = 'ইন্টেরিয়র ডিজাইনার (ক্রয়)' WHERE code = 'SUP-0135';
UPDATE supplier SET name_bn = 'ইসলাম এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0136';
UPDATE supplier SET name_bn = 'ইত্যাদি হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0137';
UPDATE supplier SET name_bn = 'জে এইচ এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0138';
UPDATE supplier SET name_bn = 'জে এম ট্রেড ইন্টারন্যাশনাল (হার্ডওয়্যার' WHERE code = 'SUP-0139';
UPDATE supplier SET name_bn = 'জে.বি.এল এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0140';
UPDATE supplier SET name_bn = 'জে.এম ট্রেডার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0141';
UPDATE supplier SET name_bn = 'জাকিয়া বিল্ডার্স হার্ডওয়্যার অ্যান্ড পি' WHERE code = 'SUP-0142';
UPDATE supplier SET name_bn = 'যমুনা হার্ডওয়্যার স্টোর (হার্ডওয়্যার)' WHERE code = 'SUP-0143';
UPDATE supplier SET name_bn = 'জনতা হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0144';
UPDATE supplier SET name_bn = 'জারা এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0145';
UPDATE supplier SET name_bn = 'জার্জ এন্টারপ্রাইজ' WHERE code = 'SUP-0146';
UPDATE supplier SET name_bn = 'জিহাদ এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0147';
UPDATE supplier SET name_bn = 'জিয়া ভাই (নতুন) (ইমপোর্টার কেরোসিন কাট)' WHERE code = 'SUP-0148';
UPDATE supplier SET name_bn = 'জিয়া ভাই ইমপোর্টার (কেরোসিন কাট-২০২০)' WHERE code = 'SUP-0149';
UPDATE supplier SET name_bn = 'জেকে ইন্টারন্যাশনাল (হার্ডওয়্যার)' WHERE code = 'SUP-0150';
UPDATE supplier SET name_bn = 'জহির ভাই (রায়ের বাজার) চায়না বোর্ড' WHERE code = 'SUP-0151';
UPDATE supplier SET name_bn = 'জুবায়েদ এন্টারপ্রাইজ (হার্ডওয়্যার' WHERE code = 'SUP-0152';
UPDATE supplier SET name_bn = 'জুঁই হার্ডওয়্যার ক্রয় (হার্ডওয়্যার)' WHERE code = 'SUP-0153';
UPDATE supplier SET name_bn = 'জুনায়েদ হার্ডওয়্যার অ্যান্ড সাপ্লায়ার্স (হার্ডওয়্যার' WHERE code = 'SUP-0154';
UPDATE supplier SET name_bn = 'জুনায়েদ এন্টারপ্রাইজ (ক্রয়)' WHERE code = 'SUP-0155';
UPDATE supplier SET name_bn = 'কে আর এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0156';
UPDATE supplier SET name_bn = 'কবির বিল্ডার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0157';
UPDATE supplier SET name_bn = 'কাকন পার্টিকেল বোর্ড এজেন্সি' WHERE code = 'SUP-0158';
UPDATE supplier SET name_bn = 'করিম এন্টারপ্রাইজ (ক্রয়)' WHERE code = 'SUP-0159';
UPDATE supplier SET name_bn = 'খাজা এন্টারপ্রাইজ (চায়না)' WHERE code = 'SUP-0160';
UPDATE supplier SET name_bn = 'খন্দকার হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0161';
UPDATE supplier SET name_bn = 'করিম এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0162';
UPDATE supplier SET name_bn = 'কাউসার এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0163';
UPDATE supplier SET name_bn = 'কেএস ইন্টারন্যাশনাল (প্লাইউড সেন্টার)' WHERE code = 'SUP-0164';
UPDATE supplier SET name_bn = 'লেটেস্ট ইন্টেরিয়র (ফরচুন)' WHERE code = 'SUP-0165';
UPDATE supplier SET name_bn = 'লক্ষ্মীপুর টুলস অ্যান্ড মেশিনারিজ (হার্ডওয়্যার' WHERE code = 'SUP-0166';
UPDATE supplier SET name_bn = 'লেভেল ৫ কর্পোরেশন (ক্রয়' WHERE code = 'SUP-0167';
UPDATE supplier SET name_bn = 'লিরা ডোরস লিঃ. ২০২৩' WHERE code = 'SUP-0168';
UPDATE supplier SET name_bn = 'লকটেক হার্ডওয়্যার ট্রেডিং (হার্ডওয়্যার)' WHERE code = 'SUP-0169';
UPDATE supplier SET name_bn = 'লাক্সারি হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0170';
UPDATE supplier SET name_bn = 'এম অ্যান্ড বি প্লাইউড ইন্ডাস্ট্রিজ. (বন্ধ/২৩)' WHERE code = 'SUP-0171';
UPDATE supplier SET name_bn = 'এম অ্যান্ড বি প্লাইউড ইন্ডাস্ট্রিজ লিঃ.' WHERE code = 'SUP-0172';
UPDATE supplier SET name_bn = 'এম কে এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0173';
UPDATE supplier SET name_bn = 'এম পি এল টেক (বারিধারা)' WHERE code = 'SUP-0174';
UPDATE supplier SET name_bn = 'এম আর সি লিমিটেড (ক্রয়.)' WHERE code = 'SUP-0175';
UPDATE supplier SET name_bn = 'এম আর এস ইন্ডাস্ট্রিজ লিঃ.' WHERE code = 'SUP-0176';
UPDATE supplier SET name_bn = 'এম আর ট্রেডার্স (ক্রয়)' WHERE code = 'SUP-0177';
UPDATE supplier SET name_bn = 'এম এস হার্ডওয়্যার স্টোর (হার্ডওয়্যার)' WHERE code = 'SUP-0178';
UPDATE supplier SET name_bn = 'এম/এস. কে.এস. কর্পোরেশন (চায়না)' WHERE code = 'SUP-0179';
UPDATE supplier SET name_bn = 'মা বাবার দোয়া হার্ডওয়্যার স্টোর (হার্ডওয়্যার' WHERE code = 'SUP-0180';
UPDATE supplier SET name_bn = 'মা এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0181';
UPDATE supplier SET name_bn = 'মা পেইন্ট' WHERE code = 'SUP-0182';
UPDATE supplier SET name_bn = 'মাহমুদা এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0183';
UPDATE supplier SET name_bn = 'মামুন বিল্ডার্স (নবাবপুর)' WHERE code = 'SUP-0184';
UPDATE supplier SET name_bn = 'মান্নান ট্রেডার্স (ক্রয়) (কে.এন.এ)' WHERE code = 'SUP-0185';
UPDATE supplier SET name_bn = 'মাস্টার পয়েন্ট (ক্রয়)' WHERE code = 'SUP-0186';
UPDATE supplier SET name_bn = 'ম্যাক্সমার্ট সি.এন.সি অ্যান্ড পেস্টিং (ক্রয়)' WHERE code = 'SUP-0187';
UPDATE supplier SET name_bn = 'মায়া পার্টিকেল লিঃ. (২০২৪)' WHERE code = 'SUP-0188';
UPDATE supplier SET name_bn = 'মায়ের দোয়া হার্ডওয়্যার অ্যান্ড পেইন্টস (হার্ডওয়্যার' WHERE code = 'SUP-0189';
UPDATE supplier SET name_bn = 'মীম এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0190';
UPDATE supplier SET name_bn = 'মেঘনা পিভিসি শিট কোম্পানি.' WHERE code = 'SUP-0191';
UPDATE supplier SET name_bn = 'মিম এন্টারপ্রাইজ-২ ধার খাত' WHERE code = 'SUP-0192';
UPDATE supplier SET name_bn = 'মীর ব্রাদার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0193';
UPDATE supplier SET name_bn = 'মিঠিন ট্রেডার্স (লুজ ভিনিয়ার)' WHERE code = 'SUP-0194';
UPDATE supplier SET name_bn = 'মিজান (হার্ডওয়্যার)' WHERE code = 'SUP-0195';
UPDATE supplier SET name_bn = 'মোবারক হোসেন অ্যান্ড ব্রাদার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0196';
UPDATE supplier SET name_bn = 'মদিনা এন্টারপ্রাইজ. (নয়াবাজার)' WHERE code = 'SUP-0197';
UPDATE supplier SET name_bn = 'মোহাম্মদ ট্রেডিং (হার্ডওয়্যার)' WHERE code = 'SUP-0198';
UPDATE supplier SET name_bn = 'মনির হার্ডওয়্যার অ্যান্ড ইলেকট্রিক (হার্ডওয়্যার)' WHERE code = 'SUP-0199';
UPDATE supplier SET name_bn = 'মুন ইন্টারন্যাশনাল (হার্ডওয়্যার' WHERE code = 'SUP-0200';
UPDATE supplier SET name_bn = 'মরিয়ম পার্টিকেল বোর্ড' WHERE code = 'SUP-0201';
UPDATE supplier SET name_bn = 'মঠবাড়িয়া বয়লার (হার্ডওয়্যার)' WHERE code = 'SUP-0202';
UPDATE supplier SET name_bn = 'মোজাফফর ভাই (এম.এইচ ট্রেড) (ক্রয়)' WHERE code = 'SUP-0203';
UPDATE supplier SET name_bn = 'মুরাদ এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0204';
UPDATE supplier SET name_bn = 'এন এন বিল্ডার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0205';
UPDATE supplier SET name_bn = 'নগর বিল্ডার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0206';
UPDATE supplier SET name_bn = 'নাহিদ এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0207';
UPDATE supplier SET name_bn = 'নাইম এন্টারপ্রাইজ (মেরিনোলাম)' WHERE code = 'SUP-0208';
UPDATE supplier SET name_bn = 'নাসির ভাই (ক্রয়)' WHERE code = 'SUP-0209';
UPDATE supplier SET name_bn = 'ন্যাশনাল হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0210';
UPDATE supplier SET name_bn = 'ন্যাশনাল পলিমার ইন্ডাস্ট্রিজ লিঃ.' WHERE code = 'SUP-0211';
UPDATE supplier SET name_bn = 'নাজিম হার্ডওয়্যার স্টোর (ক্রয়) (হর' WHERE code = 'SUP-0212';
UPDATE supplier SET name_bn = 'নতুন ডালিয়া হার্ডওয়্যার স্টোর (হার্ডওয়্যার)' WHERE code = 'SUP-0213';
UPDATE supplier SET name_bn = 'নতুন এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0214';
UPDATE supplier SET name_bn = 'নতুন জনতা হার্ডওয়্যার স্টোর (হার্ডওয়্যার)' WHERE code = 'SUP-0215';
UPDATE supplier SET name_bn = 'নতুন মক্কা মেটাল (হার্ডওয়্যার)' WHERE code = 'SUP-0216';
UPDATE supplier SET name_bn = 'নতুন রহমান এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0217';
UPDATE supplier SET name_bn = 'নতুন এসআর এন্টারপ্রাইজ (এসআরএম)' WHERE code = 'SUP-0218';
UPDATE supplier SET name_bn = 'নুহা ট্রেডিং (হার্ডওয়্যার)' WHERE code = 'SUP-0219';
UPDATE supplier SET name_bn = 'নূর মদিনা বিল্ডার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0220';
UPDATE supplier SET name_bn = 'ওয়াসিস (ভিরা)' WHERE code = 'SUP-0221';
UPDATE supplier SET name_bn = 'অদুদ এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0222';
UPDATE supplier SET name_bn = 'অলিম্পিয়া পেইন্ট অ্যান্ড হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0223';
UPDATE supplier SET name_bn = 'অমি এন্টারপ্রাইজ (ক্রয়)' WHERE code = 'SUP-0224';
UPDATE supplier SET name_bn = 'ওয়ান হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0225';
UPDATE supplier SET name_bn = 'ওপেন সোর্স-ক্রয় (মোহাম্মদপুর' WHERE code = 'SUP-0226';
UPDATE supplier SET name_bn = 'ওরিয়েন্টাল ইকো উডস লিঃ. (পিভিসি)' WHERE code = 'SUP-0227';
UPDATE supplier SET name_bn = 'ওরিয়েন্টাল ইকো উডস লিঃ. (ডব্লিউপিসি)' WHERE code = 'SUP-0228';
UPDATE supplier SET name_bn = 'পাবনা ট্রেডার্স (ক্রয়)' WHERE code = 'SUP-0229';
UPDATE supplier SET name_bn = 'প্যারেন্টস হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0230';
UPDATE supplier SET name_bn = 'পাটোয়ারী বাড্ডা (ক্রয়)' WHERE code = 'SUP-0231';
UPDATE supplier SET name_bn = 'পাটোয়ারী হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0232';
UPDATE supplier SET name_bn = 'প্লাইউড সেন্টার (ক্রয়)' WHERE code = 'SUP-0233';
UPDATE supplier SET name_bn = 'পলি এইচপিএল প্লাইউড লিঃ.' WHERE code = 'SUP-0234';
UPDATE supplier SET name_bn = 'পরাণ হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0235';
UPDATE supplier SET name_bn = 'প্রাইম বিল্ডার্স (ক্রয়) (হার্ডওয়্যার)' WHERE code = 'SUP-0236';
UPDATE supplier SET name_bn = 'প্রাইম কর্পোরেশন বিডি' WHERE code = 'SUP-0237';
UPDATE supplier SET name_bn = 'প্রাইম হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0238';
UPDATE supplier SET name_bn = 'প্রাইম সলিউশন (বেলাদর)' WHERE code = 'SUP-0239';
UPDATE supplier SET name_bn = 'প্রবাসী হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0240';
UPDATE supplier SET name_bn = 'প্রগতি এন্টারপ্রাইজ. (ক্রয়)' WHERE code = 'SUP-0241';
UPDATE supplier SET name_bn = 'আর আর এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0242';
UPDATE supplier SET name_bn = 'আর.এইচ .এম ইন্ট. (হার্ডওয়্যার)' WHERE code = 'SUP-0243';
UPDATE supplier SET name_bn = 'আর.এস এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0244';
UPDATE supplier SET name_bn = 'রফি এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0245';
UPDATE supplier SET name_bn = 'রাফিয়া কার পেইন্ট (হার্ডওয়্যার)' WHERE code = 'SUP-0246';
UPDATE supplier SET name_bn = 'রহমান অ্যান্ড সন্স (কেএনএ) (ক্রয়)' WHERE code = 'SUP-0247';
UPDATE supplier SET name_bn = 'রহমান ট্রেডিং কর্পোরেশন (ক্রয়)' WHERE code = 'SUP-0248';
UPDATE supplier SET name_bn = 'রাজধানী এন্টারপ্রাইজ' WHERE code = 'SUP-0249';
UPDATE supplier SET name_bn = 'রাজধানী হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0250';
UPDATE supplier SET name_bn = 'রামগঞ্জ হার্ডওয়্যার অ্যান্ড মেশিনারিজ (হর' WHERE code = 'SUP-0251';
UPDATE supplier SET name_bn = 'রংধনু এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0252';
UPDATE supplier SET name_bn = 'আরএফএল ইন্ডাস্ট্রিজ লিমিটেড' WHERE code = 'SUP-0253';
UPDATE supplier SET name_bn = 'রিফাত ভাই (লুজ ভিনিয়ার)' WHERE code = 'SUP-0254';
UPDATE supplier SET name_bn = 'রিয়াদ এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0255';
UPDATE supplier SET name_bn = 'আরএম ইন্টারন্যাশনাল (হার্ডওয়্যার)' WHERE code = 'SUP-0256';
UPDATE supplier SET name_bn = 'রনি এন্টারপ্রাইজ (বেঙ্গল পিভিসি)' WHERE code = 'SUP-0257';
UPDATE supplier SET name_bn = 'রনি প্লাইউড ইন্ডাস্ট্রিজ (ক্রয়)' WHERE code = 'SUP-0258';
UPDATE supplier SET name_bn = 'এস কে রহমান টিম্বার অ্যান্ড পেস্টিং (ক্রয়' WHERE code = 'SUP-0259';
UPDATE supplier SET name_bn = 'এস আর এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0260';
UPDATE supplier SET name_bn = 'এস.এম এন্টারপ্রাইজ (আবুল ভাই)' WHERE code = 'SUP-0261';
UPDATE supplier SET name_bn = 'এস.এন ইন্টারন্যাশনাল (হার্ডওয়্যার)' WHERE code = 'SUP-0262';
UPDATE supplier SET name_bn = 'এস.এস হার্ডওয়্যার স্টোর (হার্ডওয়্যার)' WHERE code = 'SUP-0263';
UPDATE supplier SET name_bn = 'সাত ট্রেডিং' WHERE code = 'SUP-0264';
UPDATE supplier SET name_bn = 'সাদেক এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0265';
UPDATE supplier SET name_bn = 'সাইফ হার্ডওয়্যার অ্যান্ড টুলস (হার্ডওয়্যার)' WHERE code = 'SUP-0266';
UPDATE supplier SET name_bn = 'সাইফুল এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0267';
UPDATE supplier SET name_bn = 'সালমান এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0268';
UPDATE supplier SET name_bn = 'সান ট্রেডিং (হার্ডওয়্যার)' WHERE code = 'SUP-0269';
UPDATE supplier SET name_bn = 'সেলিম হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0270';
UPDATE supplier SET name_bn = 'শাবাব ট্রেড ইন্টারন্যাশনাল (হার্ডওয়্যার)' WHERE code = 'SUP-0271';
UPDATE supplier SET name_bn = 'শাহীন বিল্ডার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0272';
UPDATE supplier SET name_bn = 'শাহজাহান ট্রেডার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0273';
UPDATE supplier SET name_bn = 'শাখায়াত টিম্বার (ক্রয়)' WHERE code = 'SUP-0274';
UPDATE supplier SET name_bn = 'শাকিল এন্টারপ্রাইজ (ক্রয়)' WHERE code = 'SUP-0275';
UPDATE supplier SET name_bn = 'শান্তি এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0276';
UPDATE supplier SET name_bn = 'সোহাগ হার্ডওয়্যার স্টোর' WHERE code = 'SUP-0277';
UPDATE supplier SET name_bn = 'শহীদ এন্টারপ্রাইজ. (কেবি) (ক্রয়)' WHERE code = 'SUP-0278';
UPDATE supplier SET name_bn = 'শোরভ হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0279';
UPDATE supplier SET name_bn = 'শুভ হার্ডওয়্যার অ্যান্ড ইন্টেরিয়র (হার্ডওয়্যার)' WHERE code = 'SUP-0280';
UPDATE supplier SET name_bn = 'সাইন প্যাকেজিং স্টোর ক্রয়' WHERE code = 'SUP-0281';
UPDATE supplier SET name_bn = 'সিস ইন্টারন্যাশনাল (হার্ডওয়্যার)' WHERE code = 'SUP-0282';
UPDATE supplier SET name_bn = 'এসকেএফ বিল্ডার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0283';
UPDATE supplier SET name_bn = 'এসকেএফ হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0284';
UPDATE supplier SET name_bn = 'স্কাই বিজনেস সেন্টার (হার্ডওয়্যার)' WHERE code = 'SUP-0285';
UPDATE supplier SET name_bn = 'স্কাই ডেকর (মহাখালী)' WHERE code = 'SUP-0286';
UPDATE supplier SET name_bn = 'স্মার্ট ইকো উড' WHERE code = 'SUP-0287';
UPDATE supplier SET name_bn = 'এসএমএস কর্পোরেশন (ইয়েলো)(হার্ডওয়্যার)' WHERE code = 'SUP-0288';
UPDATE supplier SET name_bn = 'সোহরাব এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0289';
UPDATE supplier SET name_bn = 'সোহেল অ্যান্ড ব্রাদার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0290';
UPDATE supplier SET name_bn = 'সোহরাব এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0291';
UPDATE supplier SET name_bn = 'সম্রাট হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0292';
UPDATE supplier SET name_bn = 'এসপি কর্পোরেশন (রেবেকা)' WHERE code = 'SUP-0293';
UPDATE supplier SET name_bn = 'এসআরএস এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0294';
UPDATE supplier SET name_bn = 'স্টার ডোর' WHERE code = 'SUP-0295';
UPDATE supplier SET name_bn = 'স্টার হার্ডওয়্যার (হার্ডওয়্যার)' WHERE code = 'SUP-0296';
UPDATE supplier SET name_bn = 'স্টার লুজ ভিনিয়ার' WHERE code = 'SUP-0297';
UPDATE supplier SET name_bn = 'স্টার পার্টিকেল বোর্ড মিলস লিঃ. (এমডিএফ)' WHERE code = 'SUP-0298';
UPDATE supplier SET name_bn = 'স্টার পার্টিকেল বোর্ড মিলস লিঃ (এমএলবি)' WHERE code = 'SUP-0299';
UPDATE supplier SET name_bn = 'স্টার পার্টিকেল বোর্ড মিলস লিঃ (পিবি)' WHERE code = 'SUP-0300';
UPDATE supplier SET name_bn = 'স্টার পার্টিকেল বোর্ড মিলস লিঃ (প্লাই)' WHERE code = 'SUP-0301';
UPDATE supplier SET name_bn = 'স্টার পার্টিকেল বোর্ড মিলস লিঃ (ভিবি)' WHERE code = 'SUP-0302';
UPDATE supplier SET name_bn = 'স্টার পার্টিকেল বোর্ড মিলস লিঃ. (পিভিসি)' WHERE code = 'SUP-0303';
UPDATE supplier SET name_bn = 'স্টার পাইপস অ্যান্ড প্লাস্টিকস লিঃ. (পিভিসি)' WHERE code = 'SUP-0304';
UPDATE supplier SET name_bn = 'স্টার জিপসাম (স্টার)' WHERE code = 'SUP-0305';
UPDATE supplier SET name_bn = 'সুজন মেটাল ওয়ার্কস(হার্ডওয়্যার)' WHERE code = 'SUP-0306';
UPDATE supplier SET name_bn = 'সুমন এন্টারপ্রাইজ (৩৯/খা, সানপাড়া)' WHERE code = 'SUP-0307';
UPDATE supplier SET name_bn = 'সান কর্পোরেশন (হার্ডওয়্যার)' WHERE code = 'SUP-0308';
UPDATE supplier SET name_bn = 'সুন্দরবন প্লাইউড ইন্ডাস্ট্রিজ' WHERE code = 'SUP-0309';
UPDATE supplier SET name_bn = 'সুপার বোর্ড মিলস লিঃ.' WHERE code = 'SUP-0310';
UPDATE supplier SET name_bn = 'সুপার- হারুন অ্যান্ড সন্স' WHERE code = 'SUP-0311';
UPDATE supplier SET name_bn = 'সুজন ইন্টারন্যাশনাল/ এরা ট্রেড ইন্টারন্যাশনাল' WHERE code = 'SUP-0312';
UPDATE supplier SET name_bn = 'টি এ এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0313';
UPDATE supplier SET name_bn = 'টি এম এ এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0314';
UPDATE supplier SET name_bn = 'তাহমিদ এন্টারপ্রাইজ (হার্ডওয়্যার)' WHERE code = 'SUP-0315';
UPDATE supplier SET name_bn = 'তাজ হার্ডওয়্যার' WHERE code = 'SUP-0316';
UPDATE supplier SET name_bn = 'তারেক হার্ডওয়্যার' WHERE code = 'SUP-0317';
UPDATE supplier SET name_bn = 'তেজার্ট হার্ডওয়্যার অ্যান্ড নাট বোল্ট' WHERE code = 'SUP-0318';
UPDATE supplier SET name_bn = 'দ্য এশিয়ান টুলস অ্যান্ড মেশিনারিজ' WHERE code = 'SUP-0319';
UPDATE supplier SET name_bn = 'ত্রি টি ইন্টারন্যাশনাল' WHERE code = 'SUP-0320';
UPDATE supplier SET name_bn = 'ইউনিক হার্ডওয়্যার' WHERE code = 'SUP-0321';
UPDATE supplier SET name_bn = 'ইউনিক উড ক্রাফটস অ্যান্ড প্লাস্টিক ইন্ডাস্ট্রিজ.' WHERE code = 'SUP-0322';
UPDATE supplier SET name_bn = 'আপ এন্টারপ্রাইজ সিএনসি অ্যান্ড পেস্টিং (ক্রয়' WHERE code = 'SUP-0323';
UPDATE supplier SET name_bn = 'উজালা পেইন্ট অ্যান্ড ইলেকট্রিক' WHERE code = 'SUP-0324';
UPDATE supplier SET name_bn = 'ভিনিয়ার হাউস (বনানী) -ক্রয়' WHERE code = 'SUP-0325';
UPDATE supplier SET name_bn = 'ভিনিয়ার ল্যাব (লুজ ভিনিয়ার)' WHERE code = 'SUP-0326';
UPDATE supplier SET name_bn = 'ভিনিয়ার ল্যাব (পিভিসি)' WHERE code = 'SUP-0327';
UPDATE supplier SET name_bn = 'ভিরা ই-শপ (এইচপিএল)' WHERE code = 'SUP-0328';
UPDATE supplier SET name_bn = 'উড ওয়ার্ল্ড প্লাইউড ইন্ডাস্ট্রি' WHERE code = 'SUP-0329';
UPDATE supplier SET name_bn = 'উডল্যান্ড প্লাইউড মিলস লিঃ.' WHERE code = 'SUP-0330';
UPDATE supplier SET name_bn = 'উডটেক প্লাইউড (প্রাঃ) লিঃ' WHERE code = 'SUP-0331';
UPDATE supplier SET name_bn = 'ইয়াসিন প্রিন্টার্স (হার্ডওয়্যার)' WHERE code = 'SUP-0332';
UPDATE supplier SET name_bn = 'ইয়াসিন বিল্ডার্স' WHERE code = 'SUP-0333';
UPDATE supplier SET name_bn = 'ইউসুফ এন্টারপ্রাইজ' WHERE code = 'SUP-0334';
UPDATE supplier SET name_bn = 'জাকির ভাই (আরএফএল অফিসার)-ক্রয়' WHERE code = 'SUP-0335';
UPDATE supplier SET name_bn = 'জম জম ইন্টেরিয়র (হার্ডওয়্যার ক্রয়)' WHERE code = 'SUP-0336';
UPDATE supplier SET name_bn = 'জিয়া স্যার অ্যাম্বার (ক্রয়)' WHERE code = 'SUP-0337';
UPDATE supplier SET name_bn = 'জিন্নাত এন্টারপ্রাইজ (চায়না)' WHERE code = 'SUP-0338';
